<?php
declare(strict_types=1);

namespace Crustum\OpenRouter\Types;

/**
 * This class keeps role types it can be possible to get.
 * No validation for the role parameter will be performed because it may differ for various models.
 */
final readonly class RoleType
{
    /**
     * User role : Represents the input or messages from the user interacting with the assistant.
     */
    public const string USER = 'user';

    /**
     * Assistant role : Represents the output or responses generated by the AI assistant.
     */
    public const string ASSISTANT = 'assistant';

    /**
     * System role : Provides instructions or context to guide the assistant's behavior.
     */
    public const string SYSTEM = 'system';

    /**
     * Function role : Messages with instructions, commands, or requests that trigger specific actions or behaviors from the assistant.
     */
    public const string FUNCTION = 'function';

    /**
     * Tool role : Messages providing utilities or resources to enhance the conversation or assist the user in achieving their objectives.
     */
    public const string TOOL = 'tool';
}
